# Generated by Django 3.0.4 on 2020-11-23 04:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date_created', models.DateField()),
                ('last_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('DOB', models.DateField(default=datetime.date(2000, 1, 1))),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('reward', models.CharField(default='NOVICE', max_length=25)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IsGoalActive',
            fields=[
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_profile.Goals')),
                ('value', models.BooleanField(default=True)),
            ],
        ),
    ]
