# Generated by Django 3.1.5 on 2021-03-17 17:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210315_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='nutrients',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
